### ISSUE TITLE
Encoding issue at STDOUT

### ISSUE THREAD

**Issue by jneubert** [gbv/wdmapper#22]
When following the hints in #21, wdmapper worked fine when the output was redirected via `>` or `-o`. 

However, with output to the console, an Unicode error occurs at the first non-ascii character:
```
$ ./wdmapper.py check P227 -i gnds.csv
#FORMAT: BEACON
#NAME: GND ID
#DESCRIPTION: Mapping from Wikidata IDs to GND IDs
#PREFIX: http://www.wikidata.org/entity/
#TARGET: http://d-nb.info/gnd/

~ Q152835|Hans von Aachen|118643525
~ Q116268|Johannes Aal|118500015
~ Q26931|Evaristo Felice Dall'Abaco|104198273
~ Q518333|Jakob Abbadie|100002307
~ Q76359|Ernst Abbe|118646419
~ Q60582|Thomas Abbt|118500074
~ Q123557|Emil Abderhalden|118643576
~ Traceback (most recent call last):
  File "./wdmapper.py", line 8, in <module>
    main()
  File "/opt/wdmapper/wdmapper/cli.py", line 105, in main
    run(*args)
  File "/opt/wdmapper/wdmapper/cli.py", line 90, in run
    wdmapper.wdmapper(command, **vars(args))
  File "/opt/wdmapper/wdmapper/wdmapper.py", line 228, in wdmapper
    args.writer.write_delta(delta)
  File "/opt/wdmapper/wdmapper/writer.py", line 20, in write_delta
    self.write_link(link)
  File "/opt/wdmapper/wdmapper/format/beacon.py", line 68, in write_link
    self.print('|'.join(token))
  File "/opt/wdmapper/wdmapper/writer.py", line 11, in print
    print(s, file=self.stream)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 19: ordinal not in range(128)
```
May still be related to my particular environment, though the settings as described in 
https://github.com/gbv/wdmapper/issues/8#issuecomment-269433390 are in place.

**Comment by jneubert** [comment]
Turns out that the settings were still wrong. The following lines in bash profile seems to fix all known issues:
```
LANG=en_US.UTF-8
LC_ALL=en_US.UTF-8
```
(`LC_ALL` alone is not sufficient.)

Output of `locale`:
```
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
