### ISSUE TITLE
Fail when checking CSV input without property

### ISSUE THREAD

**Issue by jneubert** [gbv/wdmapper#28]
When submitting a CSV input file, I get:
```
# ./wdmapper.py check -f csv -i tests/gnd_repec_test.csv
#FORMAT: BEACON

Traceback (most recent call last):
  File "./wdmapper.py", line 8, in <module>
    main()
  File "/opt/wdmapper/wdmapper/cli.py", line 113, in main
    run(*args)
  File "/opt/wdmapper/wdmapper/cli.py", line 98, in run
    wdmapper.wdmapper(command, **vars(args))
  File "/opt/wdmapper/wdmapper/wdmapper.py", line 254, in wdmapper
    for delta in deltas:
  File "/opt/wdmapper/wdmapper/wikidata.py", line 147, in get_deltas
    p_target=target.id,
AttributeError: 'NoneType' object has no attribute 'id'
```
Input was identical to that in https://github.com/gbv/wdmapper/issues/25#issue-201073143

**Comment by nichtich** [comment]
The call is equivalent to

    wdmapper check -i tests/gnd_repec_test.csv

but fails because the CSV file contains no information about properties. The program should give a hint to call with properties instead:

    wdmapper check P227 P2428 -i tests/gnd_repec_test.csv

**Comment by jneubert** [comment]
Sorry, I missed that, playing with different input files.

**Comment by nichtich** [comment]
Still there should be a better error message
